#!/bin/bash

#goal: calculate score matrix for multiple genomic location files 
#activate the environment with Deeptools
source /zfs/omics/software/v_envs/madpy3/bin/activate

# score file

# location files

#calculate the matrices forward 
for i in ~/personal/data/TE/hg19.bed
do	
	computeMatrix reference-point --referencePoint center -a 2000 -b 2000 \
	-S ~/personal/data/G4/G4seq/hg19/G4_PDS_minus_hg19.bw \
	-R ${i} \
	--missingDataAsZero \
	-o ~/personal/results/matrix/${i%.bed}G4seq_plus.gz \
	-p 8 #number of processors used
	

#calculate the matrices reverse 
for i in ~/personal/data/TE/hg19.bed
do	
	computeMatrix reference-point --referencePoint center -a 2000 -b 2000 \
	-S ~/personal/data/G4/G4seq/hg19/G4_PDS_plus_hg19.bw \
	-R ${i} \
	--missingDataAsZero \
	-o ~/personal/results/matrix/${i%.bed}G4seq_minus.gz \
	-p 8 #number of processors used

# plot heatmaps from all matrices using the same settings 
for i in ~/personal/results/matrix/*.gz
do
	plotHeatmap -m ${i} -out ${i%.gz}.png --colorMap gist_yarg --refPointLabel center --legendLocation none	--heatmapWidth 8 --heatmapHeight 10 --yMin 0

	mv ~/personal/results/matrix/*.png ~/personal/results/plots 
done
